#! /bin/sh

set -e

this_dir="$(dirname -- "$(readlink -f -- "$0")")"
export PATH="$this_dir"/usr/bin:"$PATH"
export DOTNET_ROOT="$this_dir"/usr/share/dotnet
export LD_LIBRARY_PATH="$this_dir"/usr/lib:"$LD_LIBRARY_PATH"
exec JediTerm CringeBootstrap "$@"
