<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net10.0-windows10.0.19041.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <TieredPGO>true</TieredPGO>
        <PublishReadyToRun>true</PublishReadyToRun>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        
        <!-- Required for Serialization of List<MyGameInventoryItem> in VRage.GameServices.MyInventoryHelper -->
        <!-- Deserialization is patched to use safer NrbfDecoder instead -->
        <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
        
        <ApplicationIcon>..\icon.ico</ApplicationIcon>
        <ActualHostName>SpaceEngineers</ActualHostName>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <!-- Xplat -->
    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    </PropertyGroup>

    <!-- Windows only -->
    <PropertyGroup Condition="'$(TargetFramework)' != 'net10.0'">
        <UseWindowsForms>true</UseWindowsForms>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NLog.Schema" />
        <PackageReference Include="NLog.Targets.AtomicFile" />
        <PackageReference Include="Velopack" />
        <PackageReference Include="System.Runtime.Serialization.Formatters" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CringeBootstrap.Abstractions\CringeBootstrap.Abstractions.csproj" />
      <ProjectReference Include="..\CringeLauncher\CringeLauncher.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="NLog.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
    </ItemGroup>
    
    <Target Name="ComputeMainHostOutputFile" AfterTargets="_ComputeNETCoreBuildOutputFiles" Condition="'$(ComputeNETCoreBuildOutputFiles)' == 'true'">
        <!-- Due to applications and system expecting fixed process name we must copy second instance of host to be launched as main from crashpad host -->

        <ItemGroup Condition="'$(AppHostIntermediatePath)' != ''">
            <None Include="$(AppHostIntermediatePath)">
                <Link>$(ActualHostName)$(_NativeExecutableExtension)</Link>
                <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
                <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            </None>
        </ItemGroup>
    </Target>
    
</Project>
