<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <LangVersion>preview</LangVersion>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
    </PropertyGroup>

    <ItemGroup>
        <Publicize Include="VRage:VRage.Plugins.MyPlugins.LoadPlugins" />
        <Publicize Include="SpaceEngineers.Game:SpaceEngineers.Game.SpaceEngineersGame.OnRenderInitialized" />
        <Publicize Include="Sandbox.Game:Sandbox.Engine.Platform.Game.set_DrawThread" />
        <Publicize Include="Sandbox.Game:Sandbox.MySandboxGame.form" />
        <Publicize Include="Sandbox.Game:Sandbox.MySandboxGame.RenderThread_SizeChanged" />
        <Publicize Include="VRage.Render;VRage.Render11;VRage.Platform.Windows;VRage.Scripting" IncludeCompilerGeneratedMembers="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Basic.Reference.Assemblies.Net90" Version="1.7.9" />
        <PackageReference Include="dnlib" Version="4.4.0" />
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="9.0.0" />
        <PackageReference Include="System.Management" Version="9.0.0" />
        <PackageReference Include="System.Private.ServiceModel" Version="4.10.3" />
        <PackageReference Include="Torch.SixLabors.ImageSharp" Version="1.0.0-beta6" />
        <PackageReference Include="Velopack" Version="0.0.942" />
        <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.106">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NLog" Version="5.3.4" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
        <PackageReference Include="SpaceEngineersDedicated.ReferenceAssemblies" Version="1.*" ExcludeAssets="runtime" />
        <PackageReference Include="Steamworks.NET" Version="20.1.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CringeBootstrap.Abstractions\CringeBootstrap.Abstractions.csproj" />
        <ProjectReference Include="..\CringePlugins\CringePlugins.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="NativeMethods.txt" />
    </ItemGroup>

</Project>
