<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="NLog" Version="6.0.4" />
        <PackageReference Include="SpaceEngineersDedicated.ReferenceAssemblies" Version="1.207.22" ExcludeAssets="runtime" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\CringeBootstrap.Abstractions\CringeBootstrap.Abstractions.csproj" />
    </ItemGroup>

</Project>
