<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NuGet\NuGet.csproj" />
      <ProjectReference Include="..\SharedCringe\SharedCringe.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Publicize Include="VRage:VRage.Plugins.MyPlugins.m_plugins" />
        <Publicize Include="VRage:VRage.Plugins.MyPlugins.m_handleInputPlugins" />
		<Publicize Include="VRage.Render11:VRageRender.MyCommon" />
		<Publicize Include="VRage.Render11:VRageRender.MyRender11.DeviceInstance" />
		<Publicize Include="VRage.Game:VRage.Game.MyDefinitionManagerBase.m_registeredAssemblies" />
		<Publicize Include="VRage.Game:VRage.Game.MyDefinitionManagerBase.m_registered" />
		<Publicize Include="VRage.Game:VRage.Game.ObjectBuilder.MyGlobalTypeMetadata.m_assemblies" />
		<Publicize Include="VRage:VRage.MyXmlSerializerManager.m_registeredAssemblies" />
		<Publicize Include="Sandbox.Game:Sandbox.Game.World.MySession.m_sessionComponents" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Basic.Reference.Assemblies.Net90" Version="1.8.3" PrivateAssets="all" />
        <PackageReference Include="JsonSchema.Net.Generation" Version="5.0.4" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.7" />
        <PackageReference Include="Lib.Harmony.Thin" Version="2.3.4-torch" />
        <PackageReference Include="ImGui.NET.DirectX" Version="1.92.1.5" />
        <PackageReference Include="SpaceEngineersDedicated.ReferenceAssemblies" Version="1.207.20" ExcludeAssets="runtime" />
        <PackageReference Include="dnlib" Version="4.5.0" />
        <PackageReference Include="Steamworks.NET" Version="[20.1.0]" />
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        
        <!-- It is included only because some plugins were using it previously -->
        <!-- TODO Make this a reference in each plugin project when dependencies support is shipped -->
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="splash.gif" />
    </ItemGroup>

</Project>
